# Generated by Django 4.0.3 on 2022-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiggy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(default='Paradise', max_length=30)),
                ('food', models.CharField(default='Biryani', max_length=20)),
                ('place', models.CharField(default='Secunderabad', max_length=20)),
                ('cost', models.IntegerField(default=399)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
